[package]
name = "restaurant-mf"
version = "0.1.0"
authors = ["Kenneth Lo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
